server:
  port: 8000


spring:
  # jackson
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # http file
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
      resolve-lazily: true
  # default false
  #  main:
  #    allow-circular-references: false
  # mybatis
mybatis:
  meal:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      use-generated-keys: true
      jdbc-type-for-null: null
      local-cache-scope: statement
    mapper-locations: classpath:/mapper/meal/*.xml
  mjms:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      use-generated-keys: true
      jdbc-type-for-null: null
      local-cache-scope: statement
    mapper-locations: classpath:/mapper/mjms/*.xml
app:
  id: mjms-pred
apollo:
  meta: http://10.160.9.197:8080,http://10.160.9.198:8080,http://42.193.188.51:8080
  bootstrap:
    enabled: true
    namespaces: application,mjms-datasource,meal-datasource
