logging:
  level:
    web: DEBUG
    sql: DEBUG
    org.apache.ibatis: DEBUG
    com.mjmspred: DEBUG
mybatis:
  #  meal:
  #    configuration:
  #      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mjms:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  packages-to-scan: com.mjmspred.controller